// Generated from libswscale/lum_h_scale.cl
const char *ff_opencl_source_lum_h_scale =
"#line 1 \"libswscale/lum_h_scale.cl\"\n"
"//alpha = desc -> alpha\n"
"//filterSize = instance->filter_size\n"
"//filterPos = instance->filter_pos	(read only, arr)\n"
"//filter = instance -> filter		(read only, arr)\n"
"//dstW = dstW\n"
"\n"
"//sliceH = sliceH\n"
"//sliceY = sliceY\n"
"\n"
"//uint8_t* src = desc->src->plane[0].line	(read only, uint8_t arr [sizeof(uint8_t) * dstW * sliceH])		array size unit is BYTE\n"
"//uint16_t* dst = desc->dst->plane[0].line	(write,		uint8_t arr [sizeof(uint16_t) * dstW * sliceH])\n"
"//uint8_t* src3 = desc->src->plane[3].line	(read only, uint8_t arr [sizeof(uint8_t) * dstW * sliceH])\n"
"//uint16_t* dst3 = desc->dst->plane[3].line	(write,		uint8_t arr [sizeof(uint16_t) * dstW * sliceH])\n"
"\n"
"//src0_sliceY = desc->src->plane[0].sliceY			(read only, int)\n"
"//dst0_sliceY = desc->dst->plane[0].sliceY			(read only, int)\n"
"\n"
"//src3_sliceY = desc->src->plane[3].sliceY			(read only, int)\n"
"//dst3_sliceY = desc->dst->plane[3].sliceY			(read only, int)\n"
"\n"
"//convertOn = c->lumConvertRange != NULL			(read only, int)\n"
"\n"
"//sliceH++ should be at host\n"
"\n"
"__kernel void hScale8To15_c(int dstW, int alpha,\n"
"			__global short* filter,\n"
"			__global int* filterPos, int filterSize,\n"
"			__global int* sliceHp, __global int* sliceYp, \n"
"			__global ushort* dst, __global uchar* src,\n"
"			__global ushort* dst3, __global uchar* src3,\n"
"			int convertOn,\n"
"			int src0_sliceY, __global int* dst0_sliceYp,\n"
"			int src3_sliceY, __global int* dst3_sliceYp, int cl_srcW, int cl_dstW,\\\n"
"                         int  available_lines)\n"
"\n"
"{\n"
"\n"
"    int sliceH = *sliceHp;\n"
"    int sliceY = *sliceYp;\n"
"    int dst0_sliceY = *dst0_sliceYp;\n"
"    int dst3_sliceY = *dst3_sliceYp;\n"
"    int i = get_global_id(0);\n"
"    if(i < sliceH){\n"
"\n"
"		int src_pos = (sliceY + i - src0_sliceY) * cl_srcW;\n"
"		int dst_pos = (sliceY + i - dst0_sliceY);\n"
"                while(dst_pos >= available_lines)\n"
"                    dst_pos -= available_lines;\n"
"\n"
"                dst_pos = dst_pos * cl_dstW;\n"
"\n"
"		int j;\n"
"		for (j = 0; j < dstW; j++) {\n"
"			int k;\n"
"			int srcPos = filterPos[j];\n"
"			int val    = 0;\n"
"			for (k = 0; k < filterSize; k++) {\n"
"				val += ((int)src[src_pos + srcPos + k]) * filter[filterSize * j + k];\n"
"				//val += ((int)src[src_pos + srcPos + k]);\n"
"				//val += filter[filterSize * j + k];\n"
"			}\n"
"			if ((val >> 7) > (1 << 15) - 1) {\n"
"                            dst[dst_pos + j] = (1 << 15) - 1;\n"
"			} else {\n"
"                            dst[dst_pos + j] = (val >> 7);\n"
"                        }\n"
"		}\n"
"\n"
"                //tmp\n"
"		//if(convertOn){\n"
"		//	int l;\n"
"		//	for(l=0; l<dstW; l++){\n"
"		//		dst[dst_pos+l] = dst[dst_pos+l] * 14071 + 33561947 >> 14;\n"
"		//	}\n"
"		//}\n"
"		//desc->dst->plane[0].sliceH += 1;\n"
"\n"
"\n"
"        if (alpha) {\n"
"	\n"
"		int src_pos = (sliceY + i - src3_sliceY) * cl_srcW;\n"
"		int dst_pos = (sliceY + i - dst3_sliceY) * cl_dstW;\n"
"\n"
"	    //desc->dst->plane[3].sliceH += 1;\n"
"	\n"
"	    int j;\n"
"            for (j = 0; j < dstW; j++) {\n"
"	\n"
"                int k;\n"
"                int srcPos = filterPos[j];\n"
"                int val    = 0;\n"
"                for (k = 0; k < filterSize; k++) {\n"
"                    val += ((int)src[srcPos + k]) * filter[filterSize * j + k];\n"
"                }\n"
"	\n"
"		if ((val >> 7) >(1 << 15) - 1)\n"
"			dst[dst_pos + j] = (1 << 15) - 1;\n"
"		else\n"
"			dst[dst_pos + j] = (val >> 7);\n"
"	\n"
"            }\n"
"	\n"
"        }   //if(desc->alpha) end\n"
"	\n"
"    }\n"
"\n"
"}\n"
"\n"
"/*\n"
"    int i;\n"
"    for (i = 0; i < dstW; i++) {\n"
"        int j;\n"
"        int srcPos = filterPos[i];\n"
"        int val    = 0;\n"
"        for (j = 0; j < filterSize; j++) {\n"
"            val += ((int)src[srcPos + j]) * filter[filterSize * i + j];\n"
"        }\n"
"        dst[i] = FFMIN(val >> 7, (1 << 15) - 1); // the cubic equation does overflow ...\n"
"    }\n"
"*/\n"
"\n"
;
